'Dataset' : 'Argoverse'

'Model' : 'NeuralPrior'

'Loss' :
  # from dataset
  'fov_up': fov_up,
  'fov_down': fov_down,
  'proj_H': proj_H,
  'proj_W': proj_W,
  'max_range': max_range,
  'margin': 0.01,
  'both_ways' : True,

  # Smooth
  'sm_normals_K' : 8,
  'K': 5,
  'forward_weight' : 1,
  'smooth_weight' : 1,

  # Chamfer
  'free_weight' : 1,
  'ch_normals_K' : 0,
  'nn_weights' : 2,
  'nn_max_radius' : 2,
  'smoothness_weight' : 0.1,

'Optimization' :
  'early_patience' : 10,
  '--lr' : 0.008,
  'iters' : 5000,
  'early_min_delta' : 0.001
